FROM cschranz/gpu-jupyter:v1.6_cuda-12.0_ubuntu-22.04
WORKDIR /home/jovyan/work
ENV GRANT_SUDO=yes
ENV JUPYTER_ENABLE_LAB=yes
user root

RUN apt update && apt install -y python3 python3-pip libgomp1
RUN pip install --upgrade setuptools pip
RUN pip install pycaret[analysis,models,mlops] --ignore-installed PyYAML==6.0.1
RUN pip uninstall mlflow -y
RUN pip install mlflow==2.7.1
RUN pip install temporalio
